services:
  user-service:
    image: golang:alpine
    working_dir: /app
    volumes:
      - ../studExE4-user-service:/app
    ports:
      - "9081:9081"
    environment:
      - USER_SERVICE_PORT=9081
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=studexdb_users
    command: go run cmd/server/main.go

  driver-service:
    image: golang:alpine
    working_dir: /app
    volumes:
      - ../studExE4-driver-service:/app
    ports:
      - "9082:9082"
    environment:
      - DRIVER_SERVICE_PORT=9082
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=studexdb_drivers
      - USER_SERVICE_URL=http://user-service:9081
    command: go run cmd/server/main.go
    depends_on:
      - user-service

  trip-service:
    image: golang:alpine
    working_dir: /app
    volumes:
      - ../studExE4-trip-service:/app
    ports:
      - "9083:9083"
    environment:
      - TRIP_SERVICE_PORT=9083
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=studexdb_orders
      - USER_SERVICE_URL=http://user-service:9081
      - DRIVER_SERVICE_URL=http://driver-service:9082
      - CALLBACK_URL=http://api-gateway:9080/callback/order-accepted
    command: go run cmd/server/main.go
    depends_on:
      - user-service
      - driver-service

  api-gateway:
    image: golang:alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "9080:9080"
    environment:
      - PORT=9080
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=studexdb
      - USER_SERVICE_URL=http://user-service:9081
      - DRIVER_SERVICE_URL=http://driver-service:9082
      - TRIP_SERVICE_URL=http://trip-service:9083
      - CUSTOMER_BOT_URL=http://customer-bot:9084
    command: go run cmd/main.go
    depends_on:
      - user-service
      - driver-service
      - trip-service

  customer-bot:
    image: golang:latest
    working_dir: /app
    volumes:
      - ../studExE4-customer-bot:/app
    stdin_open: true
    tty: true
    environment:
      - API_GATEWAY_URL=http://api-gateway:9080
      - CALLBACK_PORT=9084
    command: go run cmd/main.go
    depends_on:
      - api-gateway

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "9085:8080"
    environment:
      URLS: '[{"url":"/spec/openapi-user-service.yaml","name":"User Service"},{"url":"/spec/openapi-driver-service.yaml","name":"Driver Service + Admin"},{"url":"/spec/openapi-trip-service.yaml","name":"Trip Service"},{"url":"/spec/openapi-bot.yaml","name":"Customer Bot"},{"url":"/spec/openapi-gateway.yaml","name":"API Gateway"}]'
      URLS_PRIMARY_NAME: "User Service"
    volumes:
      - ../studExE4-user-service/docs/openapi.yaml:/usr/share/nginx/html/spec/openapi-user-service.yaml
      - ../studExE4-driver-service/docs/openapi.yaml:/usr/share/nginx/html/spec/openapi-driver-service.yaml
      - ../studExE4-trip-service/docs/openapi.yaml:/usr/share/nginx/html/spec/openapi-trip-service.yaml
      - ../studExE4-customer-bot/docs/openapi.yaml:/usr/share/nginx/html/spec/openapi-bot.yaml
      - ./docs/openapi.yaml:/usr/share/nginx/html/spec/openapi-gateway.yaml

